### ISSUE TITLE
[Bug]: I already update..

### ISSUE THREAD

**Issue by elemen1069** [LiteLDev/LiteLoader#1439]
### Describe the bug

https://github.com/LiteLDev/LeviLamina/issues/1437#issue-2086692420

I already updated the server version to 0.5.0 but plugin loading does not work

### To Reproduce

.

### Expected behavior

.

### Screenshots

.

### Platform

windows 11 pro

### Version

0.5.0

### Additional context

.

**Comment by Dofes** [comment]
Due to a cache-related issue in lip, the 0.5.0 update may encounter problems. As an alternative, you can manually download the [release file](https://github.com/LiteLDev/LeviLamina/releases/download/v0.5.0/levilamina-windows-x64.zip) for the update, or wait for the 0.5.1 version, which will be released soon.
