### ISSUE TITLE
Event's

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#186]
Please portable ALL events from Nukkit kernel to LiteLoader

**Comment by ambiennt** [comment]
Then why don't you switch to Nukkit then, since all you seem to do is constantly ask for help and make your problems someone else's. Porting all nukkit events simply isnt feasible due to the structure of BDS and how it handles events. The unfortunate, yet inevitable part of modding a closed source program is that its _difficult_. You need to take a lot of your own liberties in trying to develop plugins and build the SDK. Judging by your limited amount of patience for trying to troubleshoot bugs and unwillingness to explore different strategies on your own, I think an open source and more-mod friendly server software will be more appropriate for you. This is in reference to your past questions: At the very least, if you want to post a question, you should be explaining what you tried, your expected results, actual results, etc.

**Comment by MCBEPluginModer** [comment]
> Then why don't you switch to Nukkit then, since all you seem to do is constantly ask for help and make your problems someone else's. Porting all nukkit events simply isnt feasible due to the structure of BDS and how it handles events. The unfortunate, yet inevitable part of modding a closed source program is that its _difficult_. You need to take a lot of your own liberties in trying to develop plugins and build the SDK. Judging by your limited amount of patience for trying to troubleshoot bugs and unwillingness to explore different strategies on your own, I think an open source and more-mod friendly server software will be more appropriate for you. This is in reference to your past questions: At the very least, if you want to post a question, you should be explaining what you tried, your expected results, actual results, etc.

No! Before I asked for help a bunch of times myself tried to implement everything, looking for the right functions, engaged in debugging, etc.!

**Comment by Jaciezyt** [comment]
There are many **basic** events in LiteLoader.Their basic principle is `Hook`.That means if there isn't any event you want,you can make one with `Hook` and other functions by yourself.
Asking LLDev for all your needs isnot good.Just PR,ok?

**Comment by MCBEPluginModer** [comment]
> There are many **basic** events in LiteLoader.Their basic principle is `Hook`.That means if there isn't any event you want,you can make one with `Hook` and other functions by yourself.
> Asking LLDev for all your needs isnot good.Just PR,ok?

No, because your job is to facilitate plugin development, not to force others to dig through bds code!

**Comment by KawaiiNahida** [comment]
We have no time to port everything from Nukkit. It's impossible for team like us. You Must Learn "HOW TO HOOK ON YOUR OWN" if you want to make great plugins.

**Comment by MCBEPluginModer** [comment]
> We have no time to port everything from Nukkit. It's impossible for team like us. You Must Learn "HOW TO HOOK ON YOUR OWN" if you want to make great plugins.

Then tell me at least what functions I need to hook to prohibit certain crafts?
