### ISSUE TITLE
Licence Issue

### ISSUE THREAD

**Issue by gentlegiantJGC** [LiteLDev/LiteLoader#647]
The AGPL licence does not allow the addition of restrictive terms.
I understand why you want to add the server hosting term but I think it is invalid due to the terms of the licence.
I just wanted to let you know.

```
All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.
```

**Comment by KawaiiNahida** [comment]
We are sorry for the problem with License due to our negligence. For some historical reasons we have a strong desire to make sure any actual changes to the main project open source. However, we do not want to force plugins that linked to LiteLoader to be opensource, this would absolutely ruin our community. We are going to review our License as soon as possible and make the appropriate changes to meet Minecraft EULA's requirement and our need.

**Comment by gentlegiantJGC** [comment]
I am not a lawyer but I believe all GLP licences (GLP, AGPL, LGPL) allow you to add terms that remove restrictions but not terms that add restrictions.

The Minecraft EULA term isn't really necessary but isn't doing any harm. Users have to agree to it independently of your licence.

Thinking about it more I think the AGPL licence forces open sourcing of private modifications so the point I originally had issue with is okay. I don't think this is the case for LGPL.

I would suggest sticking with AGPL so that any modifications for use in a service (eg server hosting) have to be open sourced and add the linking exception from LGPL so that plugins do not have to be licenced as AGPL. Not entirely sure how that would be done.
