### ISSUE TITLE
SymDB2.exe virus detection

### ISSUE THREAD

**Issue by Tschrock** [LiteLDev/LiteLoader#88]
**Describe the bug**
The SymDB2.exe file included in this repository and in the release download is setting off my antivirus software. Uploading to VirusTotal shows over 50% detection for this file:
https://www.virustotal.com/gui/file/b21d744b0ecb0adcb0f88ef9c1d34f1ff72fd36daf183a8587e1dfdc17b9842f/detection
![1638010528-p3EQ](https://user-images.githubusercontent.com/2406499/143678754-8cb079ab-614a-48c3-b0bc-86249a392f19.png)

It's possible this is a false positive, but I cannot find any source code for this file, so I can't build it myself to check.

**Comment by ShrBox** [comment]
Anti-virus software generally does not trust the exe packaged by VMProtect without sign

**Comment by ShrBox** [comment]
We will upload the signed exe

**Comment by KawaiiNahida** [comment]
well we dose want's to open-source those applicant like symdb2, however there are always someone want's to copy our code and release as part of commercial solutions. And it's hard to prevent, we plan's to obfuscate some of our private code with obfuscator so that anti-virus programs will not detect it as a virus. our temperatue solution is let our sponser check the binary file and signed it with Microsoft authorized cert

**Comment by KawaiiNahida** [comment]
![Screenshot 2021-12-09 at 09-09-01 SymDB2 exe - Jotti's malware scan](https://user-images.githubusercontent.com/42824603/145315997-0db0ae1b-6ce6-4db8-b87d-749821d95d4d.png)
![Screenshot 2021-12-09 at 09-03-15 微步在线云沙箱](https://user-images.githubusercontent.com/42824603/145316005-f149bbc5-6c81-4a38-9138-875fc8cfb38d.png)

**Comment by KawaiiNahida** [comment]
@Tschrock
